project_id = "xqxggeceacpkpgvbsspw"

[functions.process-scrape]
verify_jwt = true

[functions.send-job-notification]
verify_jwt = true

[functions.process-scheduled-jobs]
verify_jwt = true

[functions.preview-url]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = true

[functions.export-to-google-sheets]
verify_jwt = true

[functions.audit-revenue]
verify_jwt = true

[functions.trigger-sales-call]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.predict-lead-score]
verify_jwt = false

[functions.bulk-predict-leads]
verify_jwt = false

[functions.create-square-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false
