project_id = "xqxggeceacpkpgvbsspw"

[functions.process-scrape]
verify_jwt = true

[functions.send-job-notification]
verify_jwt = true

[functions.process-scheduled-jobs]
verify_jwt = true

[functions.preview-url]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.trigger-webhook]
verify_jwt = true

[functions.export-to-google-sheets]
verify_jwt = true
